# Generated by Django 6.0.4 on 2026-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('casual', 'Casual')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_min',
            field=models.IntegerField(default=0),
        ),
    ]
