# Generated by Django 6.0.4 on 2026-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], max_length=10),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
